name: Release Pipeline

on: 
  workflow_dispatch: 
    branches: 
      - main

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SSH_KEY_BASE64: ${{ secrets.AWS_SSH_KEY_BASE64 }}
  JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
  JENKINS_PASSWORD: ${{ secrets.JENKINS_PASSWORD }}
  JENKINS_EMAIL: ${{ secrets.JENKINS_EMAIL }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  TABLE_NAME: ${{ secrets.TABLE_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_AMI: ${{ secrets.AWS_AMI }}
  AWS_ITYPE: ${{ secrets.AWS_ITYPE }}
  AWS_KEYNAME: ${{ secrets.AWS_KEYNAME }}
  AWS_SECGROUPNAME: ${{ secrets.AWS_SECGROUPNAME }}

jobs: 
  release-pipeline: 
    name: Release Pipeline using Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./Terraform/Pipeline
    steps: 
    - uses: actions/checkout@v3
      name: GitHub Checkout
    - name: Replace Backend Placeholder BUCKET_NAME
      run: python3 ../../Utilities/replacer.py backend.tf backend.tf ~bucketname~ $BUCKET_NAME
    - name: Replace Backend Placeholder TABLE_NAME
      run: python3 ../../Utilities/replacer.py backend.tf backend.tf ~tablename~ $TABLE_NAME
    - name: Replace Backend Placeholder AWS_REGION
      run: python3 ../../Utilities/replacer.py backend.tf backend.tf ~region~ $AWS_REGION
    - name: Replace Placeholder AWS_REGION
      run: python3 ../../Utilities/replacer.py terraform.tfvars terraform.tfvars ~region~ $AWS_REGION
    - name: Replace Placeholder AWS_AMI
      run: python3 ../../Utilities/replacer.py terraform.tfvars terraform.tfvars ~ami~ $AWS_AMI
    - name: Replace Placeholder AWS_ITYPE
      run: python3 ../../Utilities/replacer.py terraform.tfvars terraform.tfvars ~itype~ $AWS_ITYPE
    - name: Replace Placeholder AWS_KEYNAME
      run: python3 ../../Utilities/replacer.py terraform.tfvars terraform.tfvars ~keyname~ $AWS_KEYNAME
    - name: Replace Placeholder AWS_SECGROUPNAME
      run: python3 ../../Utilities/replacer.py terraform.tfvars terraform.tfvars ~secgroupname~ $AWS_SECGROUPNAME
    - name: Decode and Save SSH Key
      run: mkdir files && echo $AWS_SSH_KEY_BASE64 | base64 -i --decode > files/id_rsa
    - name: Terraform Init
      run: terraform init
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Destroy
      run: terraform destroy --auto-approve
    - name: Delete SSH Key
      if: always()
      run: rm files/id_rsa