name: Release Jenkins

on: 
  workflow_dispatch: 
    branches: 
      - main

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SSH_KEY_BASE64: ${{ secrets.AWS_SSH_KEY_BASE64 }}

jobs: 
  release-jenkins: 
    name: Release Jenkins using Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./Terraform/Jenkins
    steps: 
    - uses: actions/checkout@v3
      name: GitHub Checkout
    - name: Decode and Save SSH Key
      run: mkdir files && echo $AWS_SSH_KEY_BASE64 | base64 -i --decode > files/id_rsa
    - name: Terraform Init
      run: terraform init
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Destroy
      run: terraform destroy --auto-approve
    - name: Delete SSH Key
      if: always()
      run: rm files/id_rsa